/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package major_project;

import java.nio.file.Paths;
import java.util.List;

import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javafx.scene.media.MediaPlayer.Status;
import javafx.application.Application;
import javafx.application.HostServices;
import javafx.stage.Stage;
import major_project.model.apiWrapper;
import major_project.model.input.DummyEngine;
import major_project.model.input.InputEngine;
import major_project.model.input.MainEngine;
import major_project.model.output.DummyOutput;
import major_project.model.output.OutputEngine;
import major_project.model.output.mainOutputEngine;
import major_project.view.MainView;

public class App extends Application {
    private InputEngine model;
    private OutputEngine outputmodel;
    private MainView view;
    private final HostServices hostServices = getHostServices();
    private final apiWrapper api = new apiWrapper();

    public static void main(String[] args) {

        if (args.length < 2) {
            System.out.println("argument should be either online or offline!!");
            System.exit(0);
        }
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) {
        List<String> args = getParameters().getRaw();
        if (args.get(0).equals("offline")) {
            model = new DummyEngine();
        } else if (args.get(0).equals("online")) {
            model = new MainEngine(api);
        } else {
            System.out.println("argument should be either online or offline!!");
            System.exit(-1);
        }
        if (args.get(1).equals("offline")) {
            outputmodel = new DummyOutput();
        } else if (args.get(1).equals("online")) {
            outputmodel = new mainOutputEngine(api);
        } else {
            System.out.println("argument should be either online or offline!!");
            System.exit(-1);
        }
        // String s = "src/main/resources/music.mp3";
        // Media h = new Media(Paths.get(s).toUri().toString());
        // MediaPlayer mediaPlayer = new MediaPlayer(h);
        // mediaPlayer.play();
        // if (mediaPlayer.getStatus() != Status.PLAYING) {
        // mediaPlayer.play();
        // }
        view = new MainView(model, outputmodel, hostServices);
        primaryStage.setScene(view.getScene());
        primaryStage.setTitle("Crypto");
        primaryStage.show();
    }

}
